drop database ems;
create database ems
use EMS;

-- comment this line for the very first time
	drop table if exists EMPLOYEE;

-- create the table EMPLOYEE
CREATE TABLE EMPLOYEE(
  EMPID INT PRIMARY KEY,
  EMPNAME VARCHAR(20) NOT NULL,
  EMPEMAIL VARCHAR(30) NOT NULL,
  EMPMOBNO BIGINT NOT NULL,
  EMPDPTNAME VARCHAR(20),
  EMPDATEJOINED DATE NOT NULL,
  EMPMGRID INT ,
  FOREIGN KEY (EMPMGRID) REFERENCES EMPLOYEE(EMPID),
  EMPLEAVEBALANCE INT
  );

  -- create table LEAVE_HISTORY
  drop table leave_history
  
 CREATE TABLE LEAVEHISTORY(
  LEAID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  LEASTARTDATE DATE NOT NULL,
  LEAENDDATE DATE NOT NULL,
  LEANOOFDAYS INT,
  LEAREASON VARCHAR(100),
  LEATYPE ENUM ('EL'),
  LEAAPPLIEDON DATE,
  LEAMGRCOMMENTS VARCHAR(100),
  EMPID INT(11),
  FOREIGN KEY (EMPID) REFERENCES EMPLOYEE(EMPID),
  LEASTATUS ENUM('APPROVED','DENIED','PENDING')
  );
  
  
  use  ems
  select * from LEAVEHISTORY
  truncate leavehistory
  
  INSERT INTO EMPLOYEE (EMPID,EMPNAME, EMPEMAIL,EMPMOBNO,EMPDPTNAME,EMPDATEJOINED, EMPMGRID, EMPLEAVEBALANCE) VALUES
(1000,'SHUBHAM GUPTA', 'SHUBHAMG2@HEXAWARE.COM', 8878339946,'CEO','2017-11-14', NULL,4), 
(2000,'YUVARAJ SANKAR', 'YUVARAJSANKARJ@HEXAWARE.COM',8883315009,'BI ', '2017-11-14',1000, 0),
(3000,'MANASWINI PANDA', 'MANASWINIP@HEXAWARE.COM',7064672738, 'HRM','2017-11-14',1000, 15),
(4000,'ANKITA', 'ANKITA2@HEXAWARE.COM', 8825792015,'BI','2017-11-14',2000, 5),
(5000,'PRIYA TRIPATHY', 'PRIYAT@HEXAWARE.COM',9090505919,'HRM','2017-11-14',3000, 7);


select * from Employee 

select * from leavehistory